"""入库错误码和异常。"""
from __future__ import annotations

from enum import StrEnum


class IngestErrorCode(StrEnum):
    CORRUPT_FILE = "CORRUPT_FILE"
    PDF_ENCRYPTED = "PDF_ENCRYPTED"
    PDF_TOO_LARGE = "PDF_TOO_LARGE"
    PDF_NO_TEXT_LAYER = "PDF_NO_TEXT_LAYER"
    EMPTY_CONTENT = "EMPTY_CONTENT"
    FILENAME_CONFLICT = "FILENAME_CONFLICT"
    SOURCE_CONFLICT = "SOURCE_CONFLICT"
    ARTIFACT_WRITE_FAILED = "ARTIFACT_WRITE_FAILED"
    INDEX_FAILED = "INDEX_FAILED"
    EMBEDDING_FAILED = "EMBEDDING_FAILED"
    UNSUPPORTED_MIME = "UNSUPPORTED_MIME"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    OCR_UNAVAILABLE = "OCR_UNAVAILABLE"
    OCR_FAILED = "OCR_FAILED"
    INTERNAL = "INTERNAL"
    CANCELLED = "CANCELLED"
    MAX_ATTEMPTS_EXCEEDED = "MAX_ATTEMPTS_EXCEEDED"
    WORKER_LEASE_EXPIRED = "WORKER_LEASE_EXPIRED"


class IngestError(Exception):
    def __init__(self, code: IngestErrorCode | str, message: str) -> None:
        """为入库失败附加稳定错误码。"""
        self.code = code
        self.message = message
        super().__init__(message)


CORRUPT_FILE = IngestErrorCode.CORRUPT_FILE
PDF_ENCRYPTED = IngestErrorCode.PDF_ENCRYPTED
PDF_TOO_LARGE = IngestErrorCode.PDF_TOO_LARGE
PDF_NO_TEXT_LAYER = IngestErrorCode.PDF_NO_TEXT_LAYER
EMPTY_CONTENT = IngestErrorCode.EMPTY_CONTENT
FILENAME_CONFLICT = IngestErrorCode.FILENAME_CONFLICT
SOURCE_CONFLICT = IngestErrorCode.SOURCE_CONFLICT
ARTIFACT_WRITE_FAILED = IngestErrorCode.ARTIFACT_WRITE_FAILED
INDEX_FAILED = IngestErrorCode.INDEX_FAILED
EMBEDDING_FAILED = IngestErrorCode.EMBEDDING_FAILED
UNSUPPORTED_MIME = IngestErrorCode.UNSUPPORTED_MIME
FILE_TOO_LARGE = IngestErrorCode.FILE_TOO_LARGE
OCR_UNAVAILABLE = IngestErrorCode.OCR_UNAVAILABLE
OCR_FAILED = IngestErrorCode.OCR_FAILED
INTERNAL = IngestErrorCode.INTERNAL
CANCELLED = IngestErrorCode.CANCELLED
MAX_ATTEMPTS_EXCEEDED = IngestErrorCode.MAX_ATTEMPTS_EXCEEDED
WORKER_LEASE_EXPIRED = IngestErrorCode.WORKER_LEASE_EXPIRED
